### ISSUE TITLE
[Agent] Exception throw on Agent spin up "✘ [ERROR] Uncaught Error: got rollback for nonexistent object"

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [UpstreetAI/monorepo#323]
- Commented out the ```this.chatSpecifications.leaveAll()``` in the handleJoin flow
- Initiated chat with local agent via "usdk chat '/Users/abdurrehmansubhani/Desktop/agents/testAgent10' -g".
- Exception thrown "✘ [ERROR] Uncaught (in promise) Error: got rollback for nonexistent object: players:3594d3ef-f8a3-4e4d-a076-82081de8ff3b"

Logs:

```
[wrangler:inf] - http://127.0.0.1:10618
[wrangler:inf] - http://192.168.100.146:10618
⎔ Starting local server...
worker request POST http://localhost:10618/join
initial chat specifications [
  {
    room: 'room:MPEMIQ03',
    endpointUrl: 'wss://multiplayer.isekaichat.workers.dev'
  }
]
chat specification already exists: {
  id: 'room:MPEMIQ03:wss://multiplayer.isekaichat.workers.dev',
  created_at: '2024-10-15T04:46:32.752539+00:00',
  user_id: '3594d3ef-f8a3-4e4d-a076-82081de8ff3b',
  data: {
    room: 'room:MPEMIQ03',
    endpoint_url: 'wss://multiplayer.isekaichat.workers.dev'
  },
  uid: '21b65a89-c02d-4c82-9bce-99a83cf6d039'
}

✘ [ERROR] Uncaught Error: got rollback for nonexistent object: players:3594d3ef-f8a3-4e4d-a076-82081de8ff3b

      at applyUpdateObject (file:///Users/abdurrehmansubhani/Desktop/agents/testAgent10/packages/upstreet-agent/packages/react-agents/lib/multiplayer/public/data-client.mjs:817:17)
      at mainMessage (file:///Users/abdurrehmansubhani/Desktop/agents/testAgent10/packages/upstreet-agent/packages/react-agents/lib/multiplayer/public/data-client.mjs:1223:31)


✘ [ERROR] ErrorEvent {

    filename: '',
    message: 'Uncaught Error: got rollback for nonexistent object: players:3594d3ef-f8a3-4e4d-a076-82081de8ff3b',
    lineno: 0,
    colno: 0,
    error: [Error: got rollback for nonexistent object: players:3594d3ef-f8a3-4e4d-a076-82081de8ff3b] {
      [stack]: [Getter/Setter],
      [message]: 'got rollback for nonexistent object: players:3594d3ef-f8a3-4e4d-a076-82081de8ff3b'
    },
    type: 'error',
    eventPhase: 2,
    composed: false,
    bubbles: false,
    cancelable: false,
    defaultPrevented: false,
    returnValue: true,
    currentTarget: WebSocket {
      binaryType: 'arraybuffer',
      readyState: 3,
      url: 'wss://multiplayer.isekaichat.workers.dev/api/room/realm:room:MPEMIQ03/websocket?playerId=3594d3ef-f8a3-4e4d-a076-82081de8ff3b',
      protocol: null,
      extensions: null
    },
    srcElement: WebSocket {
      binaryType: 'arraybuffer',
      readyState: 3,
      url: 'wss://multiplayer.isekaichat.workers.dev/api/room/realm:room:MPEMIQ03/websocket?playerId=3594d3ef-f8a3-4e4d-a076-82081de8ff3b',
      protocol: null,
      extensions: null
    },
    timeStamp: 0,
    isTrusted: true,
    cancelBubble: false,
    NONE: 0,
    CAPTURING_PHASE: 1,
    AT_TARGET: 2,
    BUBBLING_PHASE: 3
  }


✘ [ERROR] Uncaught (in promise) Error: got rollback for nonexistent object: players:3594d3ef-f8a3-4e4d-a076-82081de8ff3b


✘ [ERROR] Uncaught (async) Error: got rollback for nonexistent object: players:3594d3ef-f8a3-4e4d-a076-82081de8ff3b

[wrangler:inf] POST /join 200 OK (5206ms)

You are "Subhani" [a55342c2-e0c4-4f61-87ae-d1e017b7e687]), chatting in room:erUZPHoN.
In the room (room:erUZPHoN):
* Thalgar the Fearless [3594d3ef-f8a3-4e4d-a076-82081de8ff3b] 
remote player joined: a55342c2-e0c4-4f61-87ae-d1e017b7e687

Subhani (you): yo
Thalgar the Fearless: Greetings, Subhani! I am Thalgar the Fearless, renowned warrior and protector of the realm. How may I be of service to you today?
Subhani (you): 
```

**Comment by AbdurrehmanSubhani** [comment]
Issue occurred during Hackathon for participants who did abruptly disconnected (internet disconnected abruptly).

Here's a basic reproduction of that scenario:

- usdk chat with an agent
- disconnect internet
- terminate usdk chat
- execute usdk chat again

Te error log:

```
✘ [ERROR] Uncaught Error: got rollback for nonexistent object: players:3594d3ef-f8a3-4e4d-a076-82081de8ff3b

      at applyUpdateObject (file:///Users/abdurrehmansubhani/Desktop/agents/testAgent10/packages/upstreet-agent/packages/react-agents/lib/multiplayer/public/data-client.mjs:817:17)
      at mainMessage (file:///Users/abdurrehmansubhani/Desktop/agents/testAgent10/packages/upstreet-agent/packages/react-agents/lib/multiplayer/public/data-client.mjs:1223:31)

```
would appear crashing the command
