### ISSUE TITLE
[Windows] usdk chat throws workerd-windows-64 not found exception

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [UpstreetAI/monorepo#521]
Steps to reproduce:

- Latest dev branch code 
- install usdk globally from dev branch
- create a new agent
- initiate chat with the new agent
- expect the exception to be thrown

complete exception logs:

```
 usdk chat c:\Users\PC\Desktop\agents\agent1
Error: process ended without matching output:
C:\Users\PC\development\monorepo\node_modules\wrangler\wrangler-dist\cli.js:29773
            throw a;
            ^

Error: The package "@cloudflare/workerd-windows-64" could not be found, and is needed by workerd.

If you are installing workerd with npm, make sure that you don't specify the
"--no-optional" flag. The "optionalDependencies" package.json feature is used
by workerd to install the correct binary executable for your current platform.
    at generateBinPath (C:\Users\PC\development\monorepo\node_modules\workerd\lib\main.js:118:15)
    at Object.<anonymous> (C:\Users\PC\development\monorepo\node_modules\workerd\lib\main.js:152:19)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)

Node.js v22.10.0

    at Socket.onEnd (file:///C:/Users/PC/development/monorepo/packages/usdk/packages/upstreet-agent/packages/react-agents-wrangler/wrangler-runtime.mjs:56:9)
    at Socket.emit (node:events:530:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
```

![image](https://github.com/user-attachments/assets/5b4f0f67-284d-4b2b-8a42-ab01da966d3c)

**Comment by AbdurrehmanSubhani** [comment]
This issue is stale as we've moved to the node runtime for agents no
