### ISSUE TITLE
`usdk pull` broken

### ISSUE THREAD

**Issue by avaer** [UpstreetAI/monorepo#598]
Running into this trying to pull an agent:

```
pull request failed ReferenceError: extractZip is not defined
    at pull (file:///Users/xsong/.nvm/versions/node/v22.11.0/lib/node_modules/usdk/lib/create.mjs:717:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///Users/xsong/.nvm/versions/node/v22.11.0/lib/node_modules/usdk/cli.js:1670:11
    at async handleError (file:///Users/xsong/.nvm/versions/node/v22.11.0/lib/node_modules/usdk/cli.js:1377:12)
    at async Command.<anonymous> (file:///Users/xsong/.nvm/versions/node/v22.11.0/lib/node_modules/usdk/cli.js:1653:9)
    at async Command.parseAsync (/Users/xsong/.nvm/versions/node/v22.11.0/lib/node_modules/usdk/node_modules/commander/lib/command.js:1092:5)
    at async main (file:///Users/xsong/.nvm/versions/node/v22.11.0/lib/node_modules/usdk/cli.js:2113:5)
    at async file:///Users/xsong/.nvm/versions/node/v22.11.0/lib/node_modules/usdk/usdk.js:15:5
```

It's probably a bug in the `agent-deployer`.

**Comment by AbdurrehmanSubhani** [comment]
Fixed in the following:
https://github.com/UpstreetAI/monorepo/pull/600
